# Generated by Django 4.2.18 on 2025-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Partner', 'Partner'), ('Friend', 'Friend'), ('Prospect', 'Prospect')], max_length=10, unique=True)),
                ('text', models.TextField()),
                ('video_link', models.URLField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
        ),
    ]
