# Generated by Django 4.2.18 on 2025-01-26 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0002_confirmation_alter_invitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmation',
            name='invitation_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
