# Generated by Django 4.2.18 on 2025-01-30 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0003_confirmation_confirmed_confirmation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(choices=[('partenaires', 'partenaires'), ('prospects', 'prospects'), ('amis', 'amis')], max_length=20, unique=True),
        ),
    ]
