# Generated by Django 4.2.18 on 2025-02-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0004_confirmation_email_alter_invitation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='confirmed',
        ),
    ]
