# Generated by Django 4.2.18 on 2025-02-17 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='msg',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
