# Generated by Django 4.2.18 on 2025-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0008_review_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='msg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
